### ISSUE TITLE
com.alibaba.druid.pool wait millis 60000, active 100, maxActive 100 系统出现无法响应的情况

### ISSUE THREAD

**Issue by halfray** [cskefu/cskefu#835]
使用春松客服7版本，上线后不久就出现了无法访问的情况，查看用户量并不大（少于10人），对话信息也不多（少于200条）

报错信息如下： 

#2023-06-19 14:28:35.746 ^[[31mWARN ^[[0;39m o.h.e.j.spi.SqlExceptionHelper - SQL Error: 0, SQLState: null ^[[32m[ 
http-nio-8035-exec-648]^[[0;39m 
2023-06-19 14:28:35.746 ^[[1;31mERROR^[[0;39m o.h.e.j.spi.SqlExceptionHelper - wait millis 60000, active 100, max 
Active 100 ^[[32m[http-nio-8035-exec-648]^[[0;39m 
2023-06-19 14:28:35.747 ^[[1;31mERROR^[[0;39m o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet 
[dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org. 
springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; n 
ested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Unable t 
o acquire JDBC Connection] with root cause ^[[32m[http-nio-8035-exec-648]^[[0;39m 
com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 100, maxActive 100 
at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1192) 
at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1014) 
at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4544) 
at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:833) 
at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540) 
at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2723) 
at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540) 
at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:662) 
at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:4540) 
at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:992) 
at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:984) 
at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:103) 
at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(Datasour 
ceConnectionProviderImpl.java:122)

**Comment by hailiang-wang** [comment]
如果在 docker-compose yml 中配置，则在 contact center 服务上，设置环境变量

```
SPRING_DATASOURCE_DRUID_REMOVEABANDONED=true
```
对应了：`spring.datasource.druid.removeAbandoned = true` properties 文件

**Comment by hailiang-wang** [comment]
关联 BUG

https://www.cnblogs.com/shenjianjun/p/14717369.html

解决办法：

升级druid版本到1.1.24版本，另外在配置中增加了keepAlive属性，并在Application的main方法中加入System.setProperty("druid.mysql.usePingMethod", "false");

**Comment by hailiang-wang** [comment]
@halfray 您可以使用 v8 代码吗？已经提交至 https://github.com/cskefu/cskefu/commit/0166dc6dc18e4bb96146567c9074461a93a32e2d

v7 以后不会积极的维护了。

**Comment by hailiang-wang** [comment]
v8 在数据库上做了大量的调整，导致无法从 v7 平滑升级。
正是为了获得很多的好处，之前从 v3 到 v5，v5 到 v7 都是提供平滑升级的。
v8 作为长期维护版本，会提供平滑升级到高版本的。

**Comment by halfray** [comment]
v8代码发布了，我们的系统已经上线了，如果升级到v8需要做哪些操作？

**Comment by hailiang-wang** [comment]
> v8代码现在有稳定版吗，我们的系统已经上线了，如果升级到v8需要做哪些操作？

V8 功能稳定，因为做了大量的系统性能上的优化，因此在数据库和代码层面去掉了很多冗余，并且解决了若干安全漏洞。
在这么多的调整下，我们未能做到从 v7 到 v8 的 rolling upgrade(平滑升级)。

如果您调整过 v7 代码，那么需要对照着在 v8 上重新修改，如果该修改可以通过 PR 提交回社区更好。
这样大家的工作将融合，避免重复劳动。

因为 v8 的技术栈和代码层面都是从 v7 继承的，您的旧代码是可能直接复用的。
通过 PR 提交回社区是好的长久的办法。

如何为春松客服提交 PR，见

https://www.cskefu.com/2022/10/30/how-to-sign-dco-for-pr/

简单说，就是在以往的 git commit 时使用，git commit -s 
```
e.g.
git commit -s -m "update README.md and add english version"
git push origin bugfix
```

然后通过  https://github.com/cskefu/cskefu/pulls 创建 PR。

注意：push 的时候，不要直接推送到 develop|master 分支，这两个分支需要和 cskefu/cskefu 保持一致，这两个分支是从 cskefu/cskefu 同步下来的。

**Comment by hailiang-wang** [comment]
@halfray 
后来您升级代码了吗？现在的 develop 分支代码比较稳定。
develop 分支目前就是 v8.0.0, 见和 v7 相比的更新。
https://github.com/cskefu/cskefu/blob/develop/CHANGELOG.md#800

**Comment by halfray** [comment]
@hailiang-wang 安装这种方式修复以后，问答运行了2周，问题又出现了

`2023-06-30 13:45:33.679 ^[[1;31mERROR^[[0;39m o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.s
ervice() for servlet [dispatcherServlet] in context with path [] threw exception [Request pro
cessing failed; nested exception is org.springframework.transaction.CannotCreateTransactionEx
ception: Could not open JPA EntityManager for transaction; nested exception is javax.persiste
nce.PersistenceException: org.hibernate.exception.GenericJDBCException: Unable to acquire JDB
C Connection] with root cause ^[[32m[http-nio-8035-exec-9305]^[[0;39m
com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 100, maxActiv
e 100, creating 0
        at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:
1866)
at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:14
94)
at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5
058)
at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java
:909)
at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5
054)
        at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java
:2759)        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5
054)at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:
704)
        at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5
054)at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1469)`

**Comment by halfray** [comment]
目前没有时间进行升级，希望先把这个问题处理一下 @hailiang-wang

**Comment by hailiang-wang** [comment]
该问题将在分支 https://github.com/cskefu/cskefu/tree/v7 中解决，该问题为 Druid 的 BUG。
目前在 v8 中，JPA 中管理 MySQL 连接为 Spring Boot 社区的默认方案，也会有更少的 BUG。

**Comment by hailiang-wang** [comment]
@halfray 该问题已经在 https://github.com/cskefu/cskefu/commit/e0992e162a5a46621f6c3fe0929875d6f8a36876 中解决。

考虑到目前主要忙于 v8 的相关工作，以及您是从源码使用，
我没有基于该源码构建新的 docker image。

如需要构建 docker image，您可以使用脚本：

https://github.com/cskefu/cskefu/blob/v7/contact-center/admin/build.sh

**Comment by halfray** [comment]
@hailiang-wang  更换连接池后，问题又再次出现了 

报错日志：

org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityMa
nager for transaction; nested exception is org.hibernate.QueryTimeoutException: Unable to acq
uire JDBC Connection
at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.ja
va:431)
at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTran
saction(AbstractPlatformTransactionManager.java:377)
at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransac
tionIfNecessary(TransactionAspectSupport.java:463)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinT
ransaction(TransactionAspectSupport.java:277)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(Transact
ionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMet
hodInvocation.java:179)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(
PersistenceExceptionTranslationInterceptor.java:136)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMet
hodInvocation.java:179)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$Cr
udMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:140)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMet
hodInvocation.java:179)

----------------------------------------------------------

 org.hibernate.QueryTimeoutException: Unable to acquire JDBC Connection
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionType
Delegate.java:66)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQL
ExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:1
09)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:9
5)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectio
nIfNeeded(LogicalConnectionManagedImpl.java:90)
at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConne
ction(LogicalConnectionManagedImpl.java:112)
at org.hibernate.internal.SessionImpl.connection(SessionImpl.java:489)
at jdk.internal.reflect.GeneratedMethodAccessor380.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMetho
dAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:215)
at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:200)
at org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle.d
oGetConnection(HibernateJpaDialect.java:414)
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJ
paDialect.java:177)
at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.ja
va:380)
... 47 common frames omitted
Caused by: java.sql.SQLTimeoutException: Timeout after 2501ms of waiting for a connection.
at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:233)
at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:183)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:110)
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.ge
tConnection(DatasourceConnectionProviderImpl.java:122)
        at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtai
nConnection(AbstractSessionImpl.java:386)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectio
nIfNeeded(LogicalConnectionManagedImpl.java:87)
... 57 common frames omitted

MySQL端状态是无任何连接正在使用，且应用容器和MySql容器之间的网络连接状态都正常

**Comment by hailiang-wang** [comment]
根据日志可见 root cause 是

```
org.hibernate.QueryTimeoutException: Unable to acquire JDBC Connection
```

类似的解决办法，可参考

https://stackoverflow.com/questions/52426535/jdbcconnectionexception-unable-to-acquire-jdbc-connection-with-spring-boot

那么，可以设置更大的 
```
spring.datasource.hikari.maximum-pool-size
```

过程：

## 编辑 docker compose 文件

https://github.com/cskefu/cskefu/blob/28360726022e9628628d93072a6d97c881c79679/docker-compose.yml#L32

在这行后新加

```
- SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=30
```

还可以使用环境变量设置更多参数

```
# Hikari will use the above plus the following to setup connection pooling
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=30
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
```

其中，connectionTimeout 和 idleTimeout 建议设置如上。

**Comment by hailiang-wang** [comment]
@halfray 
您使用的 MySQL 是用春松客服提供的 docker 搭建的吗？

https://github.com/cskefu/cskefu/blob/28360726022e9628628d93072a6d97c881c79679/docker-compose.yml#L73

参考另外一个方法：

https://blog.csdn.net/hadues/article/details/115488104


设置环境变量
``
- SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=0
```

**Comment by hailiang-wang** [comment]
如果 MySQL 不是使用春松客服提供 mysql docker image 或 docker compose 启动，需要在 mysql 启动的时候，添加参数

![screenshot_20230715081138](https://github.com/cskefu/cskefu/assets/3538629/d23acfe4-7e17-41df-ae62-f157a424394d)

https://github.com/cskefu/cskefu/blob/28360726022e9628628d93072a6d97c881c79679/docker-compose.yml#L83

**Comment by hailiang-wang** [comment]
上一次出问题已经和标题不是一样的问题，如遇到新问题，请创建新的 issue。

**Comment by halfray** [comment]
目前才用的 MySQL 是使用春松客服提供的 mysql docker image，并采用docker compose 启动

更改前的设置：
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=2500

更改后的设置：
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=30
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=0

运行一段时间再看一下
