### ISSUE TITLE
演示地址无法发送消息

### ISSUE THREAD

**Issue by zhangchanglong** [cskefu/cskefu#836]
## 描述
https://demo.cskefu.com:443/im/text/104eac.html
![b0784e841f32ce5c4c062534b7c1ba0](https://github.com/cskefu/cskefu/assets/3481828/d1067962-f300-4cb8-8ae8-37ee889069a4)

点击发送没反应

F12查看发现 socket连接错误，印象中 演示地址 之前是没问题的，最近才出问题

## 操作系统
- [ ] Windows

**Comment by hailiang-wang** [comment]
目前，发现座席端报错，无法弹屏。

<img width="458" alt="screenshot_20230621132519" src="https://github.com/cskefu/cskefu/assets/3538629/b961a880-0b04-4685-9a68-89f54c6e82b6">

```
CSKeFu_IM.v1.js:8  Uncaught ReferenceError: orgi is not defined
    at HTMLDocument.<anonymous> (CSKeFu_IM.v1.js:8:68)
    at c (jquery-1.10.2.min.js:4:26036)
    at Object.fireWith [as resolveWith] (jquery-1.10.2.min.js:4:26840)
    at Function.ready (jquery-1.10.2.min.js:4:3305)
    at HTMLDocument.q (jquery-1.10.2.min.js:4:717)
www.google-analytics.com/g/collect?v=2&tid=G-SBBX10RKTC&gtm=45je36e2&_p=1022887300&cid=1271979925.1675231355&ul=en-us&sr=1280x720&uaa=x86&uab=64&uafvl=Not.A%252FBrand%3B8.0.0.0%7CChromium%3B114.0.5735.134%7CMicrosoft%2520Edge%3B114.0.1823.51&uamb=0&uam=&uap=Windows&uapv=15.0.0&uaw=0&ngs=1&_s=1&sid=1687324991&sct=26&seg=1&dl=https%3A%2F%2Fdemo.cskefu.com%2Fapps%2Fcontent.html&dr=https%3A%2F%2Fdemo.cskefu.com%2F&dt=%E6%98%A5%E6%9D%BE%E5%AE%A2%E6%9C%8D-%E5%BC%80%E6%BA%90%E5%AE%A2%E6%9C%8D%E7%B3%BB%E7%BB%9F&en=page_view&_ee=1:1 
        
        
        Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```
