### ISSUE TITLE
上传图片，报错500

### ISSUE THREAD

**Issue by fmyseo** [cskefu/cskefu#848]
![截图_选择区域_20230628155229](https://github.com/cskefu/cskefu/assets/44190467/e42a8f49-fe6e-4903-a3c6-123ff3d6bcda)

不管是后台，还是咨询窗口，上传图片就报错！但是看upload中，图片是上传成功了的！

**Comment by hailiang-wang** [comment]
@lecjy 看一下这个问题

**Comment by zhangchanglong** [comment]
2023-06-28 21:22:11.772 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: jakarta.persistence.TransactionRequiredException: no transaction is in progress] with root cause [http-nio-8035-exec-7] 
jakarta.persistence.TransactionRequiredException: no transaction is in progress
	at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:471)
	at org.hibernate.internal.SessionImpl.checkTransactionNeededForUpdateOperation(SessionImpl.java:2499)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1403)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1398)
	at org.springframework.orm.hibernate5.SessionFactoryUtils.flush(SessionFactoryUtils.java:113)
	at org.springframework.orm.hibernate5.SpringSessionSynchronization.beforeCommit(SpringSessionSynchronization.java:99)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerBeforeCommit(TransactionSynchronizationUtils.java:97)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerBeforeCommit(AbstractPlatformTransactionManager.java:916)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:727)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:660)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:410)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
	at com.cskefu.cc.persistence.blob.JpaBlobHelper$$SpringCGLIB$$0.createBlob(<generated>)
	at com.cskefu.cc.controller.apps.IMController.upload(IMController.java:1341)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at

**Comment by lecjy** [comment]
页面显示Whitelabel Error Page是由于javax.persistence.TransactionRequiredException: no transaction is in progress错造成的，Hibernate5.2之后遵循了JPA规范，不允许在事务外执行更新操作，保守起见，添加如下配置恢复5.2之前的默认行为即可

spring.jpa.properties.hibernate.allow_update_outside_transaction=true

**Comment by hailiang-wang** [comment]
问题没有解决。 @lecjy 

开发环境，代码 https://github.com/cskefu/cskefu/commit/306bb8e38b82255a9da0e2c58eb7fd844508f3a0

在座席工作台，上传图片后


![screenshot_20230629134337](https://github.com/cskefu/cskefu/assets/3538629/1824827d-4707-46cf-911c-8a7fc33dc06e)


报错

![screenshot_20230629134322](https://github.com/cskefu/cskefu/assets/3538629/90bf9c21-fab3-4bc3-af66-fb9226b93e06)


后台日志

```
2023-06-29 13:40:53.599 INFO  c.c.c.c.apps.AgentController - [upload] image file, agentUser id 40289f798905a906018905aa0b8b0003, paste false [http-nio-8035-exec-6] 
2023-06-29 13:40:53.702 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [http-nio-8035-exec-6] 
java.io.FileNotFoundException: ..\data\upload\600eaed8f8704386a0a0da6fdd3add7a (The system cannot find the file specified)
```
